[package]
name = "mac-font"
version = "0.1.0"
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]

[dependencies]

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.4.1"
core-text = "2.0"
core-foundation = "0.2.2"
